[project]
name = "etl-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pydantic",
    "polars",
    "black>=25.1.0",
    "apache-airflow>=3.0.4",
]
